name: Build wheels and upload to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
           FFP_CONTRACT_OFF: 1
           CIBW_ARCHS_MACOS: x86_64 arm64

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: ./wheelhouse/*.whl
  
  build_rebound_html:
    name: Compiling rebound.html
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download and install emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          emsdk/emsdk install latest
          emsdk/emsdk activate latest
      - name: Compile web client
        run: |
          bash web_client/compile.bash
      - name: Upload rebound.html
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v2
        with:
          #   tag_name: "test-tag" # Hardcoded for testing
          #   draft: true # Keep it hidden from the public
          files: |
            web_client/rebound.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: dist-source
        path: dist/*.tar.gz

  upload_all:
    needs: [build_wheels, make_sdist]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: dist-*
        merge-multiple: true
        path: dist

    - uses: pypa/gh-action-pypi-publish@release/v1
      #with:
      #  repository-url: https://test.pypi.org/legacy/
