name: REBOUND (C + MPI)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install OpenMPI
        run: sudo apt-get install -y -q openmpi-bin libopenmpi-dev
      - name: Compile all MPI examples
        working-directory: ./examples
        run: |
          make mpi
      - name: Run MPI Unit Tests (np=1)
        working-directory: ./examples/mpi_unittests
        run: |
            mpirun --oversubscribe -np 1 ./rebound
      - name: Run MPI Unit Tests (np=2)
        working-directory: ./examples/mpi_unittests
        run: |
            mpirun --oversubscribe -np 2 ./rebound
      - name: Run MPI Unit Tests (np=4)
        working-directory: ./examples/mpi_unittests
        run: |
            mpirun --oversubscribe -np 4 ./rebound
