name: REBOUND (ipynb)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest jupyter matplotlib scipy multiprocess
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build package
        run: pip install -e .
      - name: Running jupyter notebooks
        run: |
          cd ipython_examples
          python ipynb2py.py AdvWHFast.ipynb
          python ipynb2py.py Checkpoints.ipynb
          python ipynb2py.py Churyumov-Gerasimenko.ipynb
          python ipynb2py.py CloseEncounters.ipynb
          python ipynb2py.py EscapingParticles.ipynb
          python ipynb2py.py Forces.ipynb
          python ipynb2py.py FourierSpectrum.ipynb
          python ipynb2py.py Horizons.ipynb
          python ipynb2py.py Holmberg.ipynb
          python ipynb2py.py Megno.ipynb
          python ipynb2py.py Resonances_of_Jupiters_moons.ipynb
          python ipynb2py.py VariationalEquations.ipynb
          python ipynb2py.py VariationalEquationsWithChainRule.ipynb
          python ipynb2py.py UniquelyIdentifyingParticlesWithHashes.ipynb
          python ipynb2py.py RemovingParticlesFromSimulation.ipynb
          python ipynb2py.py PoincareMap.ipynb
          python ipynb2py.py OrbitalElements.ipynb
          python ipynb2py.py Testparticles.ipynb
          python ipynb2py.py Units.ipynb
          python ipynb2py.py WHFast.ipynb
          python ipynb2py.py HighOrderSymplectic.ipynb
          python ipynb2py.py TransitTimingVariations.ipynb
