name: REBOUNDx (python)

on: [push, pull_request]

jobs:
  build:
    name: Python tests on ${{ matrix.os }} (${{ matrix.python-version }})
    timeout-minutes: 10

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          path: rebound
      - uses: actions/checkout@v4
        with:
          # repository: dtamayo/reboundx
          repository: hannorein/reboundx
          path: reboundx
          ref: rebound5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip 
        run: python -m pip install --upgrade pip
      - name: Install pytest wheel and setuptools 
        run: pip install pytest wheel setuptools
      - name: Install REBOUND requirements
        run: pip install -r rebound/requirements.txt
      - name: Install REBOUNDx requirements
        run: pip install -r reboundx/requirements.txt
      - name: Build REBOUND package
        run: pip install ./rebound
      - name: Build REBOUNDx package
        run: pip install --no-build-isolation -e ./reboundx -v
      - name: Run REBOUNDx unit tests
        working-directory: reboundx
        run: python -m unittest discover -s reboundx/tests/ -v
