name: Trigger REBOUNDx CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          echo $GITHUB_SHA
          curl -L -X POST https://api.github.com/repos/dtamayo/reboundx/dispatches \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: Bearer ${{ secrets.REBX_TRIGGER_TOKEN }}' \
          -d '{"event_type": "trigger_rebx", "client_payload": {"ref": "$GITHUB_SHA$"}}'
